### ISSUE TITLE
Incorrect version on the xml markup

### ISSUE THREAD

**Issue by adelavina** [ollitapa/bitrise-step-xctest-cobertura-xml#1]
Hi,
Running v1.0 on my step, executing aftewards a Sonar scan and getting:

ERROR: Error during SonarQube Scanner execution
ERROR: Error during parsing of the generic coverage report '/Users/vagrant/deploy/cobertura.xml'. Look at SonarQube documentation to know the expected XML format.
ERROR: Caused by: Unknown report version: diff_coverage 0.1. This parser only handles version 1.
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.

Upon review of the cobertura.xml file I find:

<coverage line-rate="0.3042926378952227" branch-rate="1.0" lines-covered="2637" lines-valid="8666" timestamp="1582627971.9778972" **version="diff_coverage 0.1"** complexity="0.0" branches-valid="1.0" branches-covered="1.0">

I think a semver tag should correspond to the version of the generation.

New to Cobertura formatting tho. Apologies if I'm setting something wrong.

**Comment by ollitapa** [comment]
Nice catch! Can you verify if this branch helps? Using the step below in your bitrise.yml
`- git::https://github.com/ollitapa/bitrise-step-xctest-cobertura-xml.git@newVersion:`

**Comment by adelavina** [comment]
Thanks @ollitapa any quick documentation on how to make my bitrise workflow point to your branch for this step?

Ignore this, manually editted the yml. Testing.

**Comment by ollitapa** [comment]
https://devcenter.bitrise.io/bitrise-cli/steps/#step-referenceid-format

**Comment by adelavina** [comment]
It's looking better but still failing:

ERROR: Error during parsing of the generic coverage report '/Users/vagrant/deploy/cobertura.xml'. Look at SonarQube documentation to know the expected XML format.
ERROR: Caused by: Unknown report version: **2.0.0**. This parser only handles version 1.

I think its expecting a single "1" string for that xml node.

**Comment by ollitapa** [comment]
What version is your Sonar?

**Comment by adelavina** [comment]
SonarQube scanner step v1.0.6
Sonar server 7.9.2

**Comment by ollitapa** [comment]
Can you try to change Scanner CLI version to 4.2.0.1873

**Comment by ollitapa** [comment]
Or try this 
`- git::https://github.com/ollitapa/bitrise-step-xctest-cobertura-xml.git@oldScanner:`

**Comment by adelavina** [comment]
ERROR: Error during SonarQube Scanner execution
ERROR: Error during parsing of the generic coverage report '/Users/vagrant/deploy/cobertura.xml'. Look at SonarQube documentation to know the expected XML format.
ERROR: Caused by: Unknown report version: 2.0.0. This parser only handles version 1.
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.

Using:

INFO: SonarQube Scanner 4.2.0.1873
INFO: Java 1.8.0_232 AdoptOpenJDK (64-bit)
INFO: Mac OS X 10.14.6 x86_64
INFO: User cache: /Users/vagrant/.sonar/cache
INFO: SonarQube server 7.9.2

Want me to try the other branch?

**Comment by ollitapa** [comment]
Do you use 
`sonar.swift.coverage.reportPattern=sonar-reports/cobertura.xml` 
in your sonar-project.properties ?

You can try the other brach. It has 1.0.0 version string now

**Comment by adelavina** [comment]
Still fails unfortunately, seems it takes only the major version in this case:

`ERROR: Caused by: Unknown report version: 1.0.0. This parser only handles version 1.
`
My config:

`            sonar.projectKey=$BITRISE_APP_TITLE
            sonar.projectName=$BITRISE_APP_TITLE
            sonar.language=swift
            sonar.host.url=XXX
            sonar.login=$SONAR_LOGIN_TOKEN
            sonar.exclusions=Carthage/**, bamboo-specs/**, Frameworks/**
            sonar.swift.project=$BITRISE_PROJECT_PATH
            sonar.swift.coverage.reportPattern=/Users/vagrant/deploy
            sonar.junit.reportPaths=/Users/vagrant/deploy/cobertura.xml
            sonar.coverageReportPaths=/Users/vagrant/deploy/cobertura.xml`

As I saaid before, first time scanning swift and with this Sonar version; I need to improve the props definitiion anyway.

**Comment by ollitapa** [comment]
I don't have these lines in my properties file:
`sonar.junit.reportPaths=/Users/vagrant/deploy/cobertura.xml`
`sonar.coverageReportPaths=/Users/vagrant/deploy/cobertura.xml`
I think 
`sonar.swift.coverage.reportPattern=/Users/vagrant/deploy/cobertura.xml`
should be enough. Also make sure that your sonar server has https://github.com/Idean/sonar-swift installed.

**Comment by ollitapa** [comment]
I updated the branch oldScanner to have only version string "1"

**Comment by adelavina** [comment]
That one works propery.

The following: 

`ERROR: Error during SonarQube Scanner execution
ERROR: Error during parsing of the generic coverage report '/Users/vagrant/deploy/cobertura.xml'. Look at SonarQube documentation to know the expected XML format.
ERROR: Caused by: Unknown XML node, expected "file" but got "sources" at line 49`

Am I doing something plain wrong?

**Comment by ollitapa** [comment]
Aaa, actually this is wrong: `sonar.junit.reportPaths=/Users/vagrant/deploy/cobertura.xml ` you would need to make the junit report file with Trainer: https://github.com/fastlane-community/trainer

Can you try to run the workflow without `sonar.junit.reportPaths`

**Comment by adelavina** [comment]
With that change everything is back to working; yet sonar is showing no coverage whatsoever; it is showing line count per file tho, my config is looking like this:

`sonar.projectKey=$BITRISE_APP_TITLE
sonar.projectName=$BITRISE_APP_TITLE
sonar.language=swift
sonar.host.url=XXX
sonar.login=$SONAR_LOGIN_TOKEN
sonar.exclusions=Carthage/**, bamboo-specs/**, Frameworks/**
sonar.swift.project=$BITRISE_PROJECT_PATH
sonar.swift.coverage.reportPattern=/Users/vagrant/deploy/cobertura.xml`

While my scanner logs look like this:

INFO: ------------- Run sensors on module mb-hb-ios
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=170ms
INFO: Sensor SonarCSS Rules [cssfamily]
INFO: No CSS, PHP, HTML or VueJS files are found in the project. CSS analysis is skipped.
INFO: Sensor SonarCSS Rules [cssfamily] (done) | time=2ms
INFO: Sensor JaCoCo XML Report Importer [jacoco]
INFO: Sensor JaCoCo XML Report Importer [jacoco] (done) | time=4ms
INFO: Sensor SwiftLint [backelitesonarswiftplugin]
INFO: Sensor SwiftLint [backelitesonarswiftplugin] (done) | time=8ms
INFO: Sensor Tailor [backelitesonarswiftplugin]
INFO: Sensor Tailor [backelitesonarswiftplugin] (done) | time=1ms
INFO: Sensor Swift Squid [backelitesonarswiftplugin]
WARN: Metric 'lines' is an internal metric computed by SonarQube/SonarCloud. Provided value is ignored.
INFO: Sensor Swift Squid [backelitesonarswiftplugin] (done) | time=286ms
INFO: Sensor Surefire [backelitesonarswiftplugin]
WARN: JUnit report directory not found at /Users/vagrant/git/sonar-reports
INFO: Sensor Surefire [backelitesonarswiftplugin] (done) | time=3ms
INFO: Sensor Cobertura [backelitesonarswiftplugin]
INFO: Sensor Cobertura [backelitesonarswiftplugin] (done) | time=1ms
INFO: Sensor Lizard [backelitesonarswiftplugin]
WARN: Lizard report file not found at /Users/vagrant/git/sonar-reports/lizard-report.xml
INFO: Sensor Lizard [backelitesonarswiftplugin] (done) | time=1ms
INFO: Sensor JavaXmlSensor [java]
INFO: Sensor JavaXmlSensor [java] (done) | time=2ms
INFO: Sensor HTML [web]
INFO: Sensor HTML [web] (done) | time=5ms
INFO: ------------- Run sensors on project
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=5ms
INFO: Load project repositories
INFO: Load project repositories (done) | time=168ms
INFO: Calculating CPD for 0 files
INFO: CPD calculation finished
INFO: Analysis report generated in 131ms, dir size=239 KB
INFO: Analysis report compressed in 214ms, zip size=107 KB
INFO: Analysis report uploaded in 483ms
INFO: ANALYSIS SUCCESSFUL, you can browse XXX
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
INFO: More about the report processing at XXX?id=AXCAWsW1NjDIWAfG-x3s
INFO: Analysis total time: 7.962 s

At this point I'm not sure if its a problem on Sonar; on Cobertura or if I just failing at submitting my JUnit report which I'm generating on the test step like this:

`--color --report junit --output "${BITRISE_DEPLOY_DIR}/Test.xml"`

**Comment by ollitapa** [comment]
I think you are then missing
`sonar.junit.reportPaths=/Users/vagrant/deploy/Test.xml`

**Comment by adelavina** [comment]
I am totally lost here; none of these parameters works, either get ignored:

sonar.swift.coverage.reportPattern=/Users/vagrant/deploy/cobertura.xml
sonar.swift.junit.reportPaths=/Users/vagrant/deploy/Test.xml
sonar.cobertura.reportPath=/Users/vagrant/deploy/cobertura.xml

And the one that is documented here:
https://community.sonarsource.com/t/coverage-test-data-generate-reports-for-swift/9700

Breaks the scan:

ERROR: Error during SonarQube Scanner execution 
ERROR: Error during parsing of the generic coverage report '/Users/vagrant/deploy/cobertura.xml'. Look at SonarQube documentation to know the expected XML format. 
ERROR: Caused by: Unknown XML node, expected "file" but got "sources" at line 49

I think I'm left trying to generate it through scripts...

**Comment by ollitapa** [comment]
I suggest you make the `sonar-project.properties` file. You can take a look at mine:
https://gist.github.com/ollitapa/57bbd6911d6a1c421e1f51cf5f653e6b

**Comment by adelavina** [comment]
So it seems I managed to solve it with this:

cd /tmp
curl https://raw.githubusercontent.com/SonarSource/sonar-scanning-examples/master/swift-coverage/swift-coverage-example/xccov-to-sonarqube-generic.sh > xccov-to-sonarqube-generic.sh
chmod 777 xccov-to-sonarqube-generic.sh
./xccov-to-sonarqube-generic.sh $BITRISE_XCRESULT_PATH > sonarqube-generic-coverage.xml 

And then using that file with the scanner like this:
sonar.coverageReportPaths=/tmp/sonarqube-generic-coverage.xml

**Comment by ollitapa** [comment]
Ok, I'll close this ticket then. I'm not completely sure, but I believe that your sonar settings are not correct for the coverage file this step produces. I myself do not use the generic `sonar.coverageReportPaths` but the swift plugin specific scanners:

```bash
# JUnit report generated by run-sonar.sh is stored in sonar-reports/TEST-report.xml
# Change it only if you generate the file on your own
# The XML files have to be prefixed by TEST- otherwise they are not processed
sonar.junit.reportsPath=sonar-reports/TEST-report.xml

# Lizard report generated by run-sonar.sh is stored in sonar-reports/lizard-report.xml
# Change it only if you generate the file on your own
#sonar.swift.lizard.report=sonar-reports/lizard-report.xml

# Cobertura report generated by run-sonar.sh is stored in sonar-reports/coverage-swift.xml
# Change it only if you generate the file on your own
sonar.swift.coverage.reportPattern=sonar-reports/cobertura.xml

# OCLint report generated by run-sonar.sh is stored in sonar-reports/oclint.xml
# Change it only if you generate the file on your own
sonar.swift.swiftlint.report=sonar-reports/swiftlint.txt
```
